/**:
  ros__parameters:

    simulation:
      robot_model : 'sensors_diffbot' #Here you can add your URDF model defined in slam_sim/urdf
      robot_ns : 'r1' # Robot namespace (robot name) ----> RViz is set for this value, Do not move unless you need.
      pose : ['0.1', '0.0', '0.0', '0.0'] #Initial robot pose: x,y,z,th
      robot_base_color : '0.0 0.0 1.0 0.95' #Ign and Rviz color of the robot's main body (rgba)
      world_file : 'depot.sdf' # empty.sdf, depot.sdf
      map_file_path: 'PCD/test.pcd' #Path to the map file used by gmapping and rviz 
      

    lidar:
      lidar_frequency: 10.0              # Lidar frequency in Hz (typical value: 10 Hz)
      period: 0.1                        # Scanning period in seconds
      lidar_out_topic: '/lidar/points'   # Output topic for published point clouds

      horizontal_samples: 360            # Number of horizontal scan samples per rotation
      horizontal_resolution: 1           # Horizontal angular resolution in degrees
      horizontal_min_angle: -3.14159     # Minimum horizontal angle (radians)
      horizontal_max_angle:  3.14159     # Maximum horizontal angle (radians)

      vertical_samples: 32               # Number of vertical scan lines
      vertical_resolution: 1             # Vertical angular resolution in degrees
      vertical_min_angle: -0.78539       # Minimum vertical angle (-45°)
      vertical_max_angle:  0.78539       # Maximum vertical angle (+45°)

      min_distance: 0.2                  # Minimum measurable distance (meters)
      max_distance: 100.0                # Maximum measurable distance (meters)
      resolution: 0.017453               # Angular resolution in radians (~1°)

      
    imu:
      imu_frequency : 50.0 # The frequency of the lidar in Hz
      imu_out_topic: '/imu/data'

    localization:
      registration_method: "NDT_OMP"
      score_threshold: 2.0
      ndt_resolution: 1.0
      ndt_step_size: 0.1
      ndt_num_threads: 4
      transform_epsilon: 0.01
      voxel_leaf_size: 0.2
      scan_max_range: 100.0
      scan_min_range: 1.0
      scan_period: 0.1
      use_pcd_map: true
      map_path: "/home/snorlix/colcon_ws/src/FAST_LIO_ROS2/PCD/test.pcd"
      set_initial_pose: true
      initial_pose_x: 0.0
      initial_pose_y: 0.0
      initial_pose_z: 0.0
      initial_pose_qx: 0.0
      initial_pose_qy: 0.0
      initial_pose_qz: 0.0
      initial_pose_qw: 0.0
      use_odom: false
      use_imu: false
      enable_debug: true
      global_frame_id: map
      odom_frame_id: odom
      base_frame_id: base_link 
